# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elvis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('revision', models.CharField(max_length=20)),
                ('hasDisplay', models.BooleanField()),
                ('deviceip', models.CharField(max_length=20)),
                ('serialnumber', models.CharField(max_length=20)),
                ('deviceid', models.CharField(max_length=20)),
                ('firmware', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('availability', models.CharField(choices=[('in_use', 'In Use'), ('offline', 'Offline'), ('available', 'Available')], default='available', max_length=15)),
                ('currentuser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
