# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elvis',
            old_name='currentuser',
            new_name='current_user',
        ),
        migrations.AlterField(
            model_name='elvis',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
